---

- hosts: all
  gather_facts: no
  roles:
    - bootstrap
    - { role: wipe, tags: [ "unsafe" ], when: "wipe | bool" }
    - setup
    - timedate
    - { role: partition, tags: [ "unsafe" ] }
    - { role: filesystem, tags: [ "unsafe" ],
        when: "boot is defined or root is defined" }
    - { role: mount,
        when: "boot is defined or root is defined" }
    - mirror
    - install
    - configure
    - { role: bootloader, tags: [ "unsafe" ] }

  vars:
    charset: UTF-8
    locale: en_US

  vars_prompt:
    - name: "device"
      default: /dev/sda
      private: no

    - name: "filesystem"
      default: btrfs
      private: no

    - name: "firmware"
      default: auto
      private: no
      prompt: "firmware (auto, bios, uefi)"

    - name: "mirrorlist"
      default: https://www.archlinux.org/mirrorlist/all/
      private: no

    # - name: "packages"
    #   default: base
    #   private: no

    - name: "timezone"
      default: UTC
      private: no

    - name: "wipe"
      default: "no"
      private: no

