---

- hosts: all
  gather_facts: no
  roles:
    - bootstrap
    - { role: wipe, tags: [ "unsafe" ], when: "wipe | bool" }
    - { role: setup, what: firmware }
    - timedate
    - { role: partition, tags: [ "unsafe" ] }
    - { role: filesystem, tags: [ "unsafe" ],
        when: "boot is defined or root is defined" }
    - { role: mount,
        when: "boot is defined or root is defined" }
    - { role: setup, what: bootloader }
    - mirror
    - install
    - configure
    - { role: bootloader, tags: [ "unsafe" ] }
    - reboot

  vars:
    charset: UTF-8
    locale: en_US

  vars_prompt:
    - name: bootloader
      default: auto
      private: no
      prompt: bootloader (auto, grub, syslinux)

    - name: device
      default: /dev/sda
      private: no

    - name: filesystem
      default: btrfs
      private: no
      prompt: filesystem (btrfs, ext4)

    - name: firmware
      default: auto
      private: no
      prompt: firmware (auto, bios, uefi)

    - name: mirrorlist
      default: https://www.archlinux.org/mirrorlist/all/
      private: no

    - name: packages
      private: no

    - name: password
      default: password

    - name: reboot
      default: "no"
      private: no

    - name: timezone
      default: UTC
      private: no

    - name: wipe
      default: "no"
      private: no
