---

- name: unmount boot filesystem
  mount:
    fstype: false
    name: /mnt/boot
    src: false
    state: unmounted
  when: boot is defined

- name: unmount root filesystem
  mount:
    fstype: false
    name: /mnt
    src: false
    state: unmounted
  when: root is defined

- name: reboot
  command: reboot
  poll: 0
  when: reboot | bool
