---

- name: make boot filesystem for bios firmware
  filesystem: dev={{ boot }} fstype=ext4
  when: boot is defined and firmware == "bios"

- name: make boot filesystem for uefi firmware
  filesystem2: dev={{ boot }} fstype=fat
  when: boot is defined and firmware == "uefi"

- name: make root filesystem
  filesystem: dev={{ root }} fstype={{ filesystem }}
  when: root is defined
