---

# XXX: these tasks await for empty device

- block:

  - block:
    - name: set boot partition for uefi firmware
      set_fact:
        boot: "{{ device }}1"

    - name: create boot partition for uefi firmware
      command: sgdisk -n 1:0:{{ ef00_end }} -t 1:ef00 creates={{ boot }}

    when: firmware == 'uefi'

  when: boot is not defined

- block:

  when: root is not defined





- block:

  - block:

    - name: set partitions for btrfs filesystem
      set_fact:
        root: "{{ device }}"

    when: filesystem == 'btrfs'

  - block:
    - name: set partitions
      set_fact:
        root: '{{ device }}1'

    - name: create new partitions for bios firmware
      command: sgdisk -N 1 {{ device }} creates={{ root }}

    when: filesystem != 'btrfs'

  when: firmware == 'bios'

- block:
  - name: set partitions for uefi firmware
    set_fact:
      boot: "{{ device }}1"
      root: "{{ device }}2"

  - name: create new partitions for uefi firmware
    command: sgdisk -n 1:0:{{ ef00_end }} -t 1:ef00 -N 2 {{ device }} creates={{ root }}

  when: firmware == 'uefi'
