---

# XXX: these tasks await for an empty device

- block: # firmware == 'bios'

  - block: # root is undefined

    - block: # filesystem != 'btrfs'
      - name: set root partition
        set_fact:
          root: "{{ device }}1"

      - name: create root partition for bios firmware
        command: sgdisk -n 1:0:{{ ef00_end }} -t 1:ef00 creates={{ root }}

      when: filesystem != 'btrfs'

    - name: set root partition for btrfs filesystem
      set_fact:
        root: "{{ device }}"
      when: filesystem == 'btrfs'

    when: root is undefined

  when: firmware == 'bios'

- block: # firmware == 'uefi'

  when: firmware == 'uefi'








#############################################



- block:

  - block:
    - name: set boot partition for uefi firmware
      set_fact:
        boot: "{{ device }}1"

    - name: create boot partition for uefi firmware
      command: sgdisk -n 1:0:{{ ef00_end }} -t 1:ef00 creates={{ boot }}

    when: firmware == 'uefi'

  when: boot is not defined

- block:

  when: root is not defined





- block:

  - block:

    - name: set partitions for btrfs filesystem
      set_fact:
        root: "{{ device }}"

    when: filesystem == 'btrfs'

  - block:
    - name: set partitions
      set_fact:
        root: '{{ device }}1'

    - name: create new partitions for bios firmware
      command: sgdisk -N 1 {{ device }} creates={{ root }}

    when: filesystem != 'btrfs'

  when: firmware == 'bios'

- block:
  - name: set partitions for uefi firmware
    set_fact:
      boot: "{{ device }}1"
      root: "{{ device }}2"

  - name: create new partitions for uefi firmware
    command: sgdisk -n 1:0:{{ ef00_end }} -t 1:ef00 -N 2 {{ device }} creates={{ root }}

  when: firmware == 'uefi'
