---

- name: mount root filesystem
  mount: fstype={{ filesystem }} name=/mnt src={{ root }} state=mounted
  when: root is defined

- name: mount boot filesystem for bios firmware
  mount: fstype=ext4 name=/mnt/boot src={{ boot }} state=mounted
  when: boot is defined and firmware == "bios"

- name: mount boot filesystem for uefi firmware
  mount: fstype=vfat name=/mnt/boot src={{ boot }} state=mounted
  when: boot is defined and firmware == "uefi"
