---

- block:

  - name: install grub bootloader
    command: creates=/mnt/boot/grub/grubenv
             arch-chroot /mnt grub-install {{ device }}

  - name: make grub config
    changed_when: false
    command: arch-chroot /mnt grub-mkconfig
    register: c

  - name: update grub config
    copy: content={{ c.stdout }} dest=/mnt/boot/grub/grub.cfg

  when: bootloader == "grub"

- block:

  - name: install syslinux bootloader
    command: creates=/mnt/boot/syslinux/SYSLINUX_AUTOUPDATE
             arch-chroot /mnt syslinux-install_update -i

  # TODO: update syslinux bootloader config

  - name: update syslinux bootloader config
    debug: msg=TODO

  when: bootloader == "syslinux"
