---

# TODO: support bootloader selection when firmware == "uefi"

- block:

  - block:

    - name: install grub bootloader
      command: creates=/mnt/boot/grub/grubenv
               arch-chroot /mnt grub-install {{ device }}

    - name: make grub config
      changed_when: false
      command: arch-chroot /mnt grub-mkconfig
      register: c

    - name: update grub config
      copy: content={{ c.stdout }} dest=/mnt/boot/grub/grub.cfg

    when: bootloader == "grub"

  - block:

    - name: install syslinux bootloader
      command: creates=/mnt/boot/syslinux/SYSLINUX_AUTOUPDATE
               arch-chroot /mnt syslinux-install_update -i

    # TODO: update syslinux bootloader config

    - name: update syslinux bootloader config
      debug: msg=TODO

    when: bootloader == "syslinux"

  when: firmware == "bios"

- block:

  # TODO: it would be good to add more strong check for status of installed
  # systemd-boot and support update

  - name: check status of installed systemd-boot and efi variables
    changed_when: false
    failed_when: false
    register: s
    shell: "arch-chroot /mnt bootctl status | grep 'Title: Linux Boot Manager'"

  - name: install systemd-boot to esp and efi variables
    command: arch-chroot /mnt bootctl install
    when: s | failed

  - name: create bootloader entry
    command: creates=/mnt/boot/loader/entries/arch.conf
             install -D /mnt/usr/share/systemd/bootctl/arch.conf /mnt/boot/loader/entries/arch.conf

  - name: update bootloader entry root
    replace: dest=/mnt/boot/loader/entries/arch.conf regexp=(root=PARTUUID=).*?\s replace='\1TODO '

  - name: update bootloader entry rootfstype
    replace: dest=/mnt/boot/loader/entries/arch.conf regexp=(rootfstype=).*?\s replace='\1{{ filesystem }} '

  when: firmware == "uefi"
