---

- block:

  - name: check efi firmware
    register: p
    stat: path=/sys/firmware/efi

  - name: set firmware interface type
    set_fact:
      firmware: "{{ { false: 'bios', true: 'uefi' }[p.stat.exists] }}"

  when: firmware is not defined or firmware == 'auto'
