---

# TODO: make /tmp/.yasi path variable

- name: install base packages
  shell: creates=/tmp/.yasi.install.installbasepackages
         pacstrap /mnt && touch /tmp/.yasi.install.installbasepackages

- name: install btrfs progs
  command: creates=/mnt/usr/bin/btrfs pacstrap /mnt btrfs-progs
  when: filesystem == "btrfs"

# TODO: think about checking if packages are installed

- name: install additional packages
  command: pacstrap /mnt {{ packages }}
  when: packages != ""
