---

- name: install base packages
  command: creates=/mnt/etc/pacman.d/mirrorlist pacstrap /mnt

- name: install btrfs progs
  command: creates=/mnt/usr/bin/btrfs pacstrap /mnt btrfs-progs
  when: filesystem == "btrfs"

# TODO: think about checking if packages are installed

- name: install additional packages
  command: pacstrap /mnt {{ packages }}
  when: packages != ""
