---

- name: install base packages
  command: creates=/mnt/etc/pacman.d/mirrorlist pacstrap /mnt base

- name: install btrfs progs
  command: creates=/usr/bin/btrfs pacstrap /mnt core/btrfs-progs
  when: filesystem == "btrfs"
