---

- name: unmount boot filesystem
  mount: fstype=false name=/mnt/boot src=false state=unmounted

- name: unmount root filesystem
  mount: fstype=false name=/mnt src=false state=unmounted

- name: wipe signatures from device
  shell: blkid -o device {{ device }}* | sort -nr | xargs wipefs -a
